### ISSUE TITLE
Issue with ForgeGradle 6

### ISSUE THREAD

**Issue by CreativeMD** [Wyn-Price/CurseMaven#15]
Hey there,
I updated my workspace to 1.20 and because of this had to update ForgeGradle from 5 to 6 and Gradle from 7.4 to 8.1. Unfortunately CursveMaven does not work properly with these new versions.

It previously worked without any issues:
```implementation fg.deobf("curse.maven:rubidium-574856:4448053")```

Error:
`Could not resolve: curse.maven:rubidium-574856:4448053_mapped_official_1.20`

Might be the new ForgeGradle? I do not know. Is there any way to fix it (maybe I'm doing something wrong)?

In Regards
CreativeMD

**Comment by Wyn-Price** [comment]
Does it error without forgegradle? I.e. `implementation "curse.maven:rubidium-574856:4448053"`

**Comment by CreativeMD** [comment]
Oh nice that works. Is the fg.deobf even necessary?

**Comment by Wyn-Price** [comment]
It will be to deobfuscate the mod. If you try and run the game does it work?

Either way this is an issue with forgegradle then

**Comment by CreativeMD** [comment]
Unfortunately I cannot test it at the moment. My setup is broken, still have some issues with MixinGradle and other stuff. I will let you know as soon I can tell.

**Comment by CreativeMD** [comment]
Tested it, unfortunately launching the game does not work.

Should this issue be reported to ForgeGradle? If yes how do I describe it. What is actually going wrong?
