### ISSUE TITLE
Content Not allowed in prolog when using cursemaven

### ISSUE THREAD

**Issue by htmlcsjs** [Wyn-Price/CurseMaven#6]
I am working on a mod and i am getting these errors from trying to use cursemaven to download my mods. here is my deps:
```kotlin
repositories {
    repositories {
        maven {
            setUrl("https://cursemaven.com")
        }
    }
}

dependencies {
    "deobfCompile"("curse.maven:jei-238222:3040523")
    "deobfCompile"("curse.maven:craft_tweaker-239197:239197")
    "deobfCompile"("curse.maven:baubles-227083:2518667")
}
```

i have attached the log output 
[error.log](https://github.com/Wyn-Price/CurseMaven/files/8112046/error.log)

**Comment by Wyn-Price** [comment]
You're not correctly adding the repository. You have a repositories block inside a repositories block. Please do just:
```gradle
repositories {
    maven {
        setUrl("https://cursemaven.com")
    }
}
```

**Comment by htmlcsjs** [comment]
i fixed that, the error still occurs

**Comment by embeddedt** [comment]
FYI, I had the same error, and using  https://www.cursemaven.com as the URL fixed it for me. I figured this out by looking at the corrupted `.pom` files which contained a message about redirecting to the www version.

**Comment by Wyn-Price** [comment]
This should no longer occur, as the redirects have been removed. Could you please check @embeddedt

**Comment by embeddedt** [comment]
Looks like that issue is cleared up for me now. Thanks.

**Comment by htmlcsjs** [comment]
oh nice, thank you

**Comment by H-QueerCoded** [comment]
CurseMaven had been working fine for me, but when I recently tried to add another dependency to my project, I got this error. I've included the relevant parts of build.gradle for the particular mod that was giving the error.

```
repositories {
	maven {
        url "https://www.cursemaven.com"
    }
}

dependencies {
    deobfCompile "curse.maven:engineers-decor-313866:3783239"
}
```

**Comment by Wyn-Price** [comment]
Ah, the redirects are back! Try removing `www`

**Comment by H-QueerCoded** [comment]
yeah that worked

**Comment by Wyn-Price** [comment]
Should work with `www` now
